-- Áreas table
CREATE TABLE IF NOT EXISTS areas (
    ID INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(128) NOT NULL,
    icon VARCHAR(128) NOT NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;