-- Mensajes table
CREATE TABLE IF NOT EXISTS mensajes (
    ID INT(11) NOT NULL AUTO_INCREMENT,
    message TEXT NOT NULL,
    visible TINYINT(1) NOT NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;