-- StreamHits table for tracking audience
CREATE TABLE IF NOT EXISTS stream_hits (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    format VARCHAR(50) NOT NULL,
    referer VARCHAR(255) NOT NULL,
    referer_type VARCHAR(50) NOT NULL DEFAULT 'app',
    ip VARCHAR(45) NOT NULL,
    user_agent VARCHAR(512) NOT NULL,
    country VARCHAR(64) DEFAULT NULL,
    country_code VARCHAR(2) DEFAULT NULL,
    city VARCHAR(64) DEFAULT NULL,
    zip VARCHAR(10) DEFAULT NULL,
    lat DECIMAL(10, 7) DEFAULT NULL,
    lon DECIMAL(10, 7) DEFAULT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);