-- Tipo de Bitácora table
CREATE TABLE IF NOT EXISTS tipo_bitacora (
    ID INT(11) NOT NULL AUTO_INCREMENT,
    name TINYTEXT NOT NULL,
    turnos LONGTEXT NOT NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;